site_name: AWS SSO CLI
site_author: Aaron Turner
copyright: Copyright 2021-2023 Aaron Turner
repo_url: https://github.com/synfinatic/aws-sso-cli/
docs_dir: docs

theme:
  name: material

plugins:
  - search

nav:
  - 'Home': index.md
  - 'User Guide':
    - 'Quickstart': quickstart.md
    - 'Configuration': config.md
    - 'Commands & Usage': commands.md 
    - 'Frequently Asked Questions': FAQ.md
    - 'ECS Server Mode': ecs-server.md
    - 'Demos': demos.md
  - 'About':
    - 'License': license.md
    - 'Compared to aws-vault': aws-vault.md
  - 'Security':
    - 'Reporting Security Vulnerabilities': security.md
    - 'GPG Signing Keys':
      - 'Release Signing Key': code-sign-key.asc.md
      - 'Commit Signing Key': commit-sign-key.asc.md
  - 'Developer Notes':
    - 'Release New Version': release.md
    - 'Documentation': docs.md
