# Bump: 1
site_name: AWS SSO CLI
site_author: Aaron Turner
copyright: Copyright 2021-2024 Aaron Turner
repo_url: https://github.com/synfinatic/aws-sso-cli/
docs_dir: docs

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/asciinema-player.css

extra_javascript:
  - javascripts/asciinema-player.min.js

theme:
  name: material

plugins:
  - search
  - mkdocs-asciinema # https://pypi.org/project/mkdocs-asciinema/

nav:
  - 'Home': index.md
  - 'Quickstart': quickstart.md
  - 'Demos': demos.md
  - 'User Guide':
    - 'Configuration': config.md
    - 'Commands & Usage': commands.md 
    - 'Frequently Asked Questions': FAQ.md
  - 'ECS Server/Remote Access':
    - 'ECS Server Mode': ecs-server.md
    - 'ECS Server Commands': ecs-commands.md 
    - 'Remote Access to IAM Roles': remote-ssh.md
    - 'ECS Server API': ecs-api.md
  - 'About':
    - 'License': license.md
    - 'Compared to aws-vault': aws-vault.md
  - 'Security':
    - 'Reporting Security Vulnerabilities': security.md
    - 'GPG Signing Keys':
      - 'Release Signing Key': code-sign-key.asc.md
      - 'Commit Signing Key': commit-sign-key.asc.md
  - 'Developer Notes':
    - 'Release New Version': release.md
